# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-06-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_result', models.CharField(max_length=255, verbose_name='序列化之后的结果')),
                ('image', models.ImageField(upload_to='img', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片识别',
                'verbose_name_plural': '图片识别',
                'db_table': 'im',
            },
        ),
    ]
